### ISSUE TITLE
Request for package information failed: CERT_UNTRUSTED

### ISSUE THREAD

**Issue by concrain** [floydpink/atom-compare-files#13]
When trying to install diff-check
apm install compare-files

Request for package information failed: CERT_UNTRUSTED

**Comment by concrain** [comment]
Request for package information failed: CERT_UNTRUSTED

**Comment by concrain** [comment]
This might be a work firewall issue.  Wondering if anybody else has had the same problem.

**Comment by JamesGould123** [comment]
This may be a problem with Atom/NPM's latest releases not working together, a lot of users have been complaining about [this issue](https://discuss.atom.io/t/error-running-apm-install-behind-proxy/14812).

Can you try installing other packages and see if it's just this one or if others also throw this error?

**Comment by targeter21** [comment]
Sounds like this issue is resolved. I don't see it in the latest versions of atom and this plugin. Feel free to reopen if that is not the case.
