### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by MasterGoodwin** [floydpink/atom-compare-files#15]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (C:\Users\Goodwin\AppData\Local\atom\app-0.188.0\resources\app\src\atom.js:54:11)
setStatusMessage (C:\Users\Goodwin\.atom\packages\compare-files\lib\compare-files.js:23:7)
```

**Comment by JamesGould123** [comment]
This is the third time this issue has been opened. Could you check the issues before opening an issue in the future?

**Comment by MasterGoodwin** [comment]
Sorry, I do not understand so well all these things. I just click on this big red button 8^)
