### ISSUE TITLE
Package.getStylesheetsPath is deprecated.

### ISSUE THREAD

**Issue by charlynet7** [floydpink/atom-compare-files#17]
Hi,
I get this error using Atom v.0.191.0

Store package style sheets in the `styles/` directory instead of `stylesheets/` in the `compare-files` package
```
Package.getStylesheetsPath (C:\Users\<user>\AppData\Local\atom\app-0.191.0\resources\app\src\package.js:430:9)
Package.getStylesheetPaths (C:\Users\<user>\AppData\Local\atom\app-0.191.0\resources\app\src\package.js:441:32)
```

**Comment by targeter21** [comment]
I just put in a slew of updates to bring it up to speed with Atom 1.0. Please try updating thanks!

**Comment by targeter21** [comment]
Refactored stylesheets to styles.
