### ISSUE TITLE
Object.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by charlynet7** [floydpink/atom-compare-files#18]
Hi,
I get this error using Atom v.0.191.0

Requiring `$` from `atom` is no longer supported.
If you are using `space-pen`, please require `$` from `atom-space-pen-views`. Otherwise require `jquery` instead:
  `{$} = require 'atom-space-pen-views'`
  or
  `$ = require 'jquery'`
Add `"atom-space-pen-views": "^2.0.3"` to your package dependencies.
Or add `"jquery": "^2"` to your package dependencies.
```
Object.Object.defineProperty.get (C:\Users\<user>\AppData\Local\atom\app-0.191.0\resources\app\exports\atom.js:48:11)
Object.<anonymous> (C:\Users\<user>\.atom\packages\compare-files\lib\compare-files-view.js:33:11)
```

**Comment by targeter21** [comment]
Now using atom-space-pen-views.
