### ISSUE TITLE
Object.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by charlynet7** [floydpink/atom-compare-files#19]
Hi,
Maybe this error is equal to the #18 
If that is the case, I can close it.
Like the #18 , I get this error with Atom v.0.191.0

Requiring `$$$` from `atom` is no longer supported.
Please require `atom-space-pen-views` instead:
  `{$$$} = require 'atom-space-pen-views'`
Add `"atom-space-pen-views": "^2.0.3"` to your package dependencies.
```
Object.Object.defineProperty.get (C:\Users\<user>\AppData\Local\atom\app-0.191.0\resources\app\exports\atom.js:60:11)
Object.<anonymous> (C:\Users\<user>\.atom\packages\compare-files\lib\compare-files-view.js:34:13)
```

**Comment by targeter21** [comment]
This is a duplicate to #18. Closing.
