### ISSUE TITLE
WorkspaceView.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by mustafagursel** [floydpink/atom-compare-files#24]
May be duplicate of #19

The atom.workspaceView.statusBar global is deprecated. The global was
previously being assigned by the status-bar package, but Atom packages
should never assign globals.

In the future, this problem will be solved by an inter-package communication
API available on `atom.services`. For now, you can get a reference to the
`status-bar` element via `document.querySelector('status-bar')`.
```
WorkspaceView.Object.defineProperty.get (D:\Users\mgursel\AppData\Local\atom\app-0.196.0\resources\app.asar\node_modules\status-bar\lib\main.js:72:20)
setStatusMessage (D:\Users\mgursel\.atom\packages\compare-files\lib\compare-files.js:23:21)
atom-workspace.compare (D:\Users\mgursel\.atom\packages\compare-files\lib\compare-files.js:52:5)
CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (D:\Users\mgursel\AppData\Local\atom\app-0.196.0\resources\app.asar\src\command-registry.js:238:29)
```

**Comment by jesperronn** [comment]
@mustafagursel can you provide a pull request?  Deprecations must be fixed before support is removed June 1st, so I would like it to be easy for the maintainers to fix the warning :)

:+1:

**Comment by targeter21** [comment]
No longer using the global and no longer see any errors or deprecation warnings.
