### ISSUE TITLE
Package.activateResources is deprecated.

### ISSUE THREAD

**Issue by mustafagursel** [floydpink/atom-compare-files#28]
The context menu CSON format has changed. Please see
https://atom.io/docs/api/latest/ContextMenuManager

**Comment by Martinspire** [comment]
So when is the fix coming out? June is only a few days away now...

**Comment by ngryman** [comment]
From the readme:
> As I do not use atom as my primary editor anymore and the fact that I do not have enough time to devote to this, I have unpublished the package from atom packages and will not be maintaining this package anymore.

**Comment by Martinspire** [comment]
Ok, too bad, but has anybody been forking it then, willing to continue the work? Cause i haven't seen anybody publish something similar yet for Atom

**Comment by targeter21** [comment]
I just put in a slew of updates to bring it up to speed with Atom 1.0. Please try updating thanks!

**Comment by targeter21** [comment]
This issue should no longer be present. I updated the CSON to what it should be.
